FROM php:8.0-fpm-alpine3.14

ENV PHP_EXTENSIONS	\
	php-bcmath		\
	php-bz2		\
	php-calendar	\
	php-ctype		\
	php-curl		\
	php-dom		\
	php-exif		\
	php-fileinfo	\
	php-ftp		\
	php-gettext	\
	php-intl		\
	php-iconv		\
	php-json		\
	php-mbstring	\
	php-mysqli		\
	php-opcache	\
	php-openssl	\
	php-pdo_mysql	\
	php-phar		\
	php-posix		\
	php-session	\
	php-shmop		\
	php-simplexml	\
	php-sockets	\
	php-sysvmsg	\
	php-sysvsem	\
	php-sysvshm	\
	php-tokenizer	\
	php-xml		\
	php-xmlreader	\
	php-xmlwriter	\
	php-zip		\
	php-zlib

RUN apk update; \
    apk upgrade; \
    apk add --no-cache $PHP_EXTENSIONS; \
    docker-php-ext-install mysqli ;

COPY php/www.conf /usr/local/etc/php-fpm.d/www.conf
COPY php/php-fpm.conf /usr/local/etc/php-fpm.conf
COPY php/config.ini /usr/local/etc/php/conf.d/config.ini

