FROM nginx:alpine
LABEL Maintainer="sean bourg <sean.bourg@gmail.com>"

RUN apk update && apk upgrade; 

COPY config.d/proxy  /etc/nginx/conf.d/
COPY ssl /etc/ssl/keys

EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]