# Docker compose file for project.
# This setup includes a front facing proxy that reroutes traffic to cdn and site sercvices on an internal network. 
# Proxy also handles routing to the API services which is on both public/private networks due to required access 
# to external  services.
version: "3.3"
services:
    proxy:
        image: "nginx:alpine"
        container_name: "proxy"
        volumes:
            - ./etc/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
            - ./etc/ssl:/etc/ssl/private:ro
            - ./etc/self-signed.conf:/etc/nginx/conf.d/self-signed.conf:ro            
            - ./etc/ssl-params.conf:/etc/nginx/conf.d/ssl-params.conf:ro   
            - ./entrypoint/proxy:/docker-entrypoint.d:ro
            - ./log:/var/log/nginx:rw
        networks:
            - network-public
            - network-private
        ports:
            - 80:80
            - 443:443
        restart: always
        depends_on:
            - site
            - database
        links: 
            - site
            - database

    cdn:
        image: "nginx:alpine"
        container_name: "cdn"
        volumes:
            - ./etc/nginx-cdn.conf:/etc/nginx/conf.d/default.conf:ro            
            - ./entrypoint/cdn:/docker-entrypoint.d:ro
            - ./log:/var/log/nginx:rw
            - ./cdn:/www:ro
        networks:
            - network-private            
        ports:
            - 80:80
        restart: always            

    site:
        image: "nginx:alpine"
        container_name: "site"
        volumes:
            - ./etc/nginx-site.conf:/etc/nginx/conf.d/default.conf:ro            
            - ./entrypoint/site:/docker-entrypoint.d:ro
            - ./log:/var/log/nginx:rw
            - ./site/www:/site/www:ro
        depends_on:
            - php-fpm
        links:
            - php-fpm
        networks:
            - network-private
        ports:
            - 80:80
        restart: always

    php-fpm:
        build:
            context: ./dockerfile
            dockerfile: php
        container_name: "site-php"
        volumes:
            - ./etc/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
            - ./etc/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
            - ./etc/config.ini:/usr/local/etc/php/conf.d/config.ini:ro
            - ./site/www:/site/www:ro
            - ./site/include:/site/include:ro
            - ./site/view:/site/view:ro
            - ./site/config:/site/config:ro
        networks:
            - network-private
        restart: always

    database:
        image: mariadb:latest
        container_name: "database"
        env_file: database.env
            
        volumes:
            - ./entrypoint/database:/docker-entrypoint-initdb.d:ro
            - ./data:/var/lib/mysql:rw
        networks: 
            - network-private
            - network-public
        ports:
            - 3306:3306
        restart: always
        

networks:
    network-public:
        driver: bridge
        internal: false
        
    network-private:
        driver: bridge
        internal: true
