version: "3.8"

networks:
    network-public:
        driver: bridge
        internal: false
        
    network-private:
        driver: bridge
        internal: true

services:
    proxy:
        container_name: "${CONTAINER_NAME_PROXY:-proxy-instance}"
        build:             
            context: .
            dockerfile: Containerfile-proxy
        image: "${IMAGE_NAME_PROXY:-proxy-image}"
        networks:
            - network-public
            - network-private
        ports:
            - 80:80
            - 443:443
        restart: always
        depends_on:
            - site
            - database
        links: 
            - site
            - database

    cdn:
        container_name: "${CONTAINER_NAME_CDN:-cdn-instance}"
        build:             
            context: .
            dockerfile: Containerfile-nginx
            args:
                - BUILD_SOURCE=cdn             
        image: "${IMAGE_NAME_CDN:-cdn-image}"
        volumes:
            - ./test-site/fonts:/site/www/fonts:ro
            - ./test-site/media:/site/www/media:ro
            - ./test-site/script:/site/www/script:ro
            - ./test-site/style:/site/www/style:ro
        networks:
            - network-private            
        ports:
            - 80:80
        restart: always            

    site:
        container_name: "${CONTAINER_NAME_SITE:-site-instance}"
        build:             
            context: .
            dockerfile: Containerfile-nginx
            args:
                - BUILD_SOURCE=site                
        image: "${IMAGE_NAME_SITE:-site-image}"
        volumes:
            - ./test-site/www:/site/www:ro
        depends_on:
            - php-fpm
        links:
            - php-fpm
        networks:
            - network-private
        ports:
            - 80:80
        restart: always

    php-fpm:
        container_name: "${CONTAINER_NAME_PHP:-php-instance}"
        build:
            context: .
            dockerfile: Containerfile-php
        image: "${IMAGE_NAME_PHP:-php-image}"
        volumes:
            - ./test-site/www:/site/www:ro
            - ./test-site/include:/site/include:ro
            - ./test-site/view:/site/view:ro
            - ./test-site/config:/site/config:ro
        networks:
            - network-private
        restart: always

    database:
        container_name: "${CONTAINER_NAME_DATABASE:-test-database-instance}"
        image: mariadb:latest
        environment:
            - MYSQL_ROOT_PASSWORD=root-password
            - MYSQL_USER=website-user
            - MYSQL_PASSWORD=website-password
            - MYSQL_DATABASE=website
        networks: 
            - network-private
            - network-public
        ports:
            - 3306:3306
        restart: always        
